/* 
TO CREATE DB:
    CREATE DATABASE <dbName> OWNER <roleName> ;
TO CREATE TABLE INTO A DATABASE
    psql -U <user/roleName> -d <dbName> -f <filePath> ||
    INSERT INTO <tableName> (columns) VALUES 
        (row 1),
        (row 2), ...
        (row n) ; 
*/

CREATE TABLE IF NOT EXIST bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL, 
    url TEXT NOT NULL,
    description TEXT, 
);